views:
  - title: Aquarium
    type: sections
    max_columns: 2
    icon: mdi:fishbowl
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Light
            heading_style: title
            icon: mdi:lightbulb
          - type: tile
            entity: light.aquarium_light
            features_position: bottom
            vertical: false
            name: Light

          - type: heading
            icon: mdi:thermometer
            heading: Temperature
            heading_style: title
          - type: tile
            entity: sensor.aquarium_water_temperature
            features_position: bottom
            vertical: false
            name: Temperature
          - type: tile
            entity: binary_sensor.aquarium_water_temperature
            features_position: bottom
            vertical: false
            name: Temperature

          - type: heading
            icon: mdi:gesture-tap-button
            heading: Presets
            heading_style: title
          - type: tile
            entity: button.aquarium_preset_1
            features_position: bottom
            vertical: false
            name: Preset 1
          - type: tile
            entity: button.aquarium_preset_2
            features_position: bottom
            vertical: false
            name: Preset 2
          - type: tile
            entity: button.aquarium_preset_3
            features_position: bottom
            vertical: false
            name: Preset 3
          - type: tile
            entity: button.aquarium_preset_4
            features_position: bottom
            vertical: false
            name: Preset 4

      - type: grid
        cards:
          - type: heading
            heading: Manual
            heading_style: title
            icon: mdi:format-list-checkbox
          - type: entities
            entities:
              - entity: number.aquarium_intensity
                name: Intensity
              - entity: number.aquarium_red
                name: Red
              - entity: number.aquarium_green
                name: Green
              - entity: number.aquarium_blue
                name: Blue
              - entity: number.aquarium_white
                name: White

          - type: heading
            icon: mdi:cog
            heading_style: title
            heading: Diagnostic
          - type: tile
            entity: binary_sensor.aquarium_connectivity
            features_position: bottom
            vertical: false
            name: Connectivity
          - type: tile
            entity: update.aquarium_firmware
            features_position: bottom
            vertical: false
            name: Firmware
          - type: tile
            entity: sensor.aquarium_wifi_signal
            features_position: bottom
            vertical: false
            name: Wifi signal
          - type: tile
            entity: sensor.aquarium_uptime
            features_position: bottom
            vertical: false
            name: Uptime
          - type: tile
            entity: sensor.aquarium_bluetooth_mac_address
            features_position: bottom
            vertical: false
            name: Bluetooth MAC
            hide_state: false
          - type: tile
            entity: sensor.aquarium_wifi_mac_address
            features_position: bottom
            vertical: false
            name: Wifi MAC
          - type: tile
            entity: sensor.aquarium_ip_address
            features_position: bottom
            vertical: false
            name: IP address
          - type: tile
            entity: sensor.aquarium_ssid
            features_position: bottom
            vertical: false
            name: SSID
