views:
  - title: Aquarium
    type: sections
    max_columns: 2
    icon: mdi:fishbowl
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Light
            heading_style: title
            icon: mdi:lightbulb
          - type: tile
            entity: light.aquarium_licht
            features_position: bottom
            vertical: false
            name: Light
            grid_options:
              columns: 12
              rows: 1
          - type: entities
            entities:
              - entity: select.aquarium_lichtmodus
                name: Light mode
              - entity: select.aquarium_dynamische_modus
                name: Dynamic mode

          - type: heading
            icon: mdi:thermometer
            heading: Temperature
            heading_style: title
          - type: tile
            entity: sensor.aquarium_watertemperatuur
            features_position: bottom
            vertical: false
            name: Temperature
          - type: tile
            entity: binary_sensor.aquarium_watertemperatuur
            features_position: bottom
            vertical: false
            name: Temperature

          - type: heading
            icon: mdi:gesture-tap-button
            heading: Presets
            heading_style: title
          - type: tile
            entity: button.aquarium_preset_1
            features_position: bottom
            vertical: false
            name: Preset 1
          - type: tile
            entity: button.aquarium_preset_2
            features_position: bottom
            vertical: false
            name: Preset 2
          - type: tile
            entity: button.aquarium_preset_3
            features_position: bottom
            vertical: false
            name: Preset 3
          - type: tile
            entity: button.aquarium_preset_4
            features_position: bottom
            vertical: false
            name: Preset 4

      - type: grid
        cards:
          - type: heading
            heading: Manual
            heading_style: title
            icon: mdi:format-list-checkbox
          - type: entities
            entities:
              - entity: number.aquarium_intensiteit
                name: Intensity
              - entity: number.aquarium_red
                name: Red
              - entity: number.aquarium_groen
                name: Green
              - entity: number.aquarium_blauw
                name: Blue
              - entity: number.aquarium_wit
                name: White

          - type: heading
            icon: mdi:cog
            heading_style: title
            heading: Diagnostic
          - type: tile
            entity: binary_sensor.aquarium_connectiviteit
            features_position: bottom
            vertical: false
            name: Connectivity
          - type: tile
            entity: update.aquarium_firmware
            features_position: bottom
            vertical: false
            name: Firmware
          - type: tile
            entity: sensor.aquarium_wifi_signaal
            features_position: bottom
            vertical: false
            name: Wifi signal
          - type: tile
            entity: sensor.aquarium_uptime
            features_position: bottom
            vertical: false
            name: Uptime
          - type: tile
            entity: sensor.aquarium_bluetooth_mac_adres
            features_position: bottom
            vertical: false
            name: Bluetooth MAC
            hide_state: false
          - type: tile
            entity: sensor.aquarium_wifi_mac_adres
            features_position: bottom
            vertical: false
            name: Wifi MAC
          - type: tile
            entity: sensor.aquarium_ip_adres
            features_position: bottom
            vertical: false
            name: IP address
          - type: tile
            entity: sensor.aquarium_ssid
            features_position: bottom
            vertical: false
            name: SSID
